# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BER2_app', '0002_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='city',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
