# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BER2_app', '0003_sessions_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='city',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
